numeros_entrada = input("Escriu 10 números separats per espais: ")
numeros = list(map(int, numeros_entrada.split()))
suma_total = sum(numeros)
mitjana = suma_total / len(numeros)
numeros.append(suma_total)
numeros.append(mitjana)

print("\nNúmeros de l'usuari:", numeros[:-2])
print("Suma total:", suma_total)
print("Mitjana:", mitjana)
print("\nLlista completa:", numeros)
