
services:
  db:
    image: postgres:13
    container_name: db
    environment:  
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=rdc123
      - POSTGRES_USER=rdalmau
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: roger.sobrino@xtec.cat
      PGADMIN_DEFAULT_PASSWORD: roger123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
